#!/usr/bin/env python3
"""
Simple Template-Based Generator

Generates working scenarios from specs using templates (no LLM required).
This demonstrates the generator architecture and creates functional scenarios.
"""

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

from models.scenario_spec import ScenarioSpec, WorkflowType


class SimpleGenerator:
    """Generates scenarios using templates."""

    def __init__(self: "SimpleGenerator") -> None:
        """Initialize generator."""
        pass

    def generate_from_spec_file(self: "SimpleGenerator", spec_path: Path, output_dir: Path) -> dict[str, str]:
        """Generate scenario from spec file.

        Args:
            spec_path: Path to spec JSON file
            output_dir: Directory to write generated files

        Returns:
            Dict mapping file paths to generated content
        """
        spec_data = json.loads(spec_path.read_text())
        spec = ScenarioSpec(**spec_data)

        return self.generate(spec, output_dir)

    def generate(self: "SimpleGenerator", spec: ScenarioSpec, output_dir: Path) -> dict[str, str]:
        """Generate complete scenario code.

        Args:
            spec: ScenarioSpec to generate from
            output_dir: Directory to write files

        Returns:
            Dict of file paths to content
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        files: dict[str, str] = {}

        files["__init__.py"] = self._gen_init(spec)
        files["__main__.py"] = self._gen_main_entry(spec)
        files["README.md"] = self._gen_readme(spec)
        files["state.py"] = self._gen_state(spec)
        files["main.py"] = self._gen_main_orchestrator(spec)

        for stage in spec.stages:
            stage_files = self._gen_stage_module(spec, stage)
            files.update(stage_files)

        for file_path, content in files.items():
            full_path = output_dir / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)

        return files

    def _gen_init(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate __init__.py."""
        return f'''"""
{spec.display_name}

{spec.description}
"""

__version__ = "{spec.version}"
'''

    def _gen_main_entry(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate __main__.py."""
        return f'''"""Entry point for {spec.display_name}."""

from .main import main

if __name__ == "__main__":
    main()
'''

    def _gen_readme(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate README.md."""
        inputs_section = "\n".join([f"- `{inp.cli_flag or '--' + inp.name}`: {inp.description}" for inp in spec.inputs])

        stages_section = "\n".join(
            [f"{i + 1}. **{stage.display_name}**: {stage.description}" for i, stage in enumerate(spec.stages)]
        )

        return f"""# {spec.display_name}

{spec.description}

## Usage

```bash
python -m scenarios.{spec.name} [OPTIONS]
```

## Options

{inputs_section}

## Workflow

This scenario uses a **{spec.workflow_type.value.replace("_", " ").title()}** workflow:

{stages_section}

## Output

{", ".join([out.description for out in spec.outputs])}

## Generated by Amplifier Scenario Generator

This scenario was automatically generated. It follows Amplifier patterns for:
- State management
- Web UI integration
- Progress tracking
- Error handling
"""

    def _gen_state(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate state.py."""
        state_fields = []
        for field in spec.state_management.state_fields:
            state_fields.append(f'    {field}: str = ""')

        state_fields_str = "\n".join(state_fields) if state_fields else "    pass  # No additional state fields"

        return f'''"""State management for {spec.name}."""

from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
import json


@dataclass
class State:
    """Scenario state."""

    stage: str = "initialized"
    iteration: int = 0
{state_fields_str}


class StateManager:
    """Manages scenario state persistence."""

    def __init__(self: "StateManager", base_dir: Path) -> None:
        """Initialize state manager.

        Args:
            base_dir: Base directory for state files
        """
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self.path = self.base_dir / "state.json"
        self.state = self._load()

    def _load(self: "StateManager") -> State:
        """Load state from disk."""
        if self.path.exists():
            data = json.loads(self.path.read_text())
            return State(**data)
        return State()

    def save(self: "StateManager") -> None:
        """Save state to disk."""
        self.path.write_text(json.dumps(asdict(self.state), indent=2))

    def reset(self: "StateManager") -> None:
        """Reset state to initial values."""
        self.state = State()
        self.save()
'''

    def _gen_main_orchestrator(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate main.py orchestrator."""
        # Import statements
        imports = [
            "import asyncio",
            "import os",
            "import sys",
            "from pathlib import Path",
            "",
            "import click",
            "",
            "from amplifier.ccsdk_toolkit import ToolkitLogger",
            "from amplifier.ccsdk_toolkit.logger import LogFormat",
            "",
        ]

        for stage in spec.stages:
            imports.append(f"from .{stage.module_name} import {stage.class_name}")

        imports.append("from .state import StateManager")

        # CLI options
        cli_options = []
        for inp in spec.inputs:
            flag = inp.cli_flag or f"--{inp.name}"
            option_params = [f'"{flag}"']

            if inp.type.value == "file" or inp.type.value == "directory":
                option_params.append("type=click.Path()")
            elif inp.type.value == "integer":
                option_params.append("type=int")
            elif inp.type.value == "boolean":
                option_params.append("is_flag=True")
            elif inp.type.value == "choice":
                option_params.append(f"type=click.Choice({inp.choices})")

            option_params.append(f"required={str(inp.required)}")

            if inp.default is not None:
                option_params.append(f'default="{inp.default}"')

            if inp.help_text:
                option_params.append(f'help="{inp.help_text}"')

            cli_options.append(f"@click.option({', '.join(option_params)})")

        # Pipeline class
        pipeline_init = ["        self.state = state_manager"]
        for stage in spec.stages:
            pipeline_init.append(f"        self.{stage.module_name} = {stage.class_name}()")

        # Run method based on workflow type
        if spec.workflow_type == WorkflowType.SINGLE_PASS:
            run_method = self._gen_single_pass_run(spec)
        elif spec.workflow_type == WorkflowType.MULTI_STAGE:
            run_method = self._gen_multi_stage_run(spec)
        elif spec.workflow_type == WorkflowType.ITERATIVE:
            run_method = self._gen_iterative_run(spec)
        else:
            run_method = "        pass  # TODO: Implement run method"

        # Stage methods
        stage_methods = []
        for stage in spec.stages:
            method = f'''    async def _{stage.name}(self: "Pipeline") -> None:
        """Execute {stage.display_name} stage."""
        logger.info("Stage: {stage.display_name}")

        # TODO: Implement stage logic
        result = await self.{stage.module_name}.{stage.method_name}()

        if result:
            self.state.state.stage = "{stage.updates_stage_name or "completed"}"
            self.state.save()
'''
            stage_methods.append(method)

        # CLI parameters
        cli_params = [f"{inp.name}: str" for inp in spec.inputs]

        return f'''{chr(10).join(imports)}

log_format = LogFormat.JSON if os.getenv("AMPLIFIER_WEB_UI") else LogFormat.PLAIN
logger = ToolkitLogger(name="{spec.name}", format=log_format)


class Pipeline:
    """Orchestrates the {spec.display_name} pipeline."""

    def __init__(self: "Pipeline", state_manager: StateManager) -> None:
        """Initialize pipeline.

        Args:
            state_manager: State manager instance
        """
{chr(10).join(pipeline_init)}

{run_method}

{chr(10).join(stage_methods)}

@click.command()
{chr(10).join(cli_options)}
def main({", ".join(cli_params)}) -> None:
    """Run {spec.display_name}."""
    state_dir = Path("{spec.state_management.state_dir}")
    state_manager = StateManager(state_dir)

    pipeline = Pipeline(state_manager)

    # TODO: Pass inputs to pipeline.run()
    success = asyncio.run(pipeline.run())

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
'''

    def _gen_single_pass_run(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate run method for single-pass workflow."""
        stages = "\n            ".join([f"await self._{stage.name}()" for stage in spec.stages])
        return f'''    async def run(self: "Pipeline") -> bool:
        """Execute single-pass workflow.

        Returns:
            True if successful
        """
        logger.info("Starting {spec.display_name}")

        try:
            {stages}
            logger.info("Completed successfully")
            return True
        except Exception as e:
            logger.error(f"Failed: {{e}}")
            return False
'''

    def _gen_multi_stage_run(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate run method for multi-stage workflow."""
        stage_checks = []
        for i, stage in enumerate(spec.stages):
            prev_stage = "initialized" if i == 0 else spec.stages[i - 1].updates_stage_name or spec.stages[i - 1].name
            stage_checks.append(f'''            if self.state.state.stage == "{prev_stage}":
                await self._{stage.name}()''')

        return f'''    async def run(self: "Pipeline") -> bool:
        """Execute multi-stage workflow with resume capability.

        Returns:
            True if successful
        """
        logger.info(f"Starting from stage: {{self.state.state.stage}}")

        try:
{chr(10).join(stage_checks)}

            logger.info("Completed successfully")
            return True
        except Exception as e:
            logger.error(f"Failed: {{e}}")
            return False
'''

    def _gen_iterative_run(self: "SimpleGenerator", spec: ScenarioSpec) -> str:
        """Generate run method for iterative workflow."""
        if not spec.iteration:
            return "        pass  # Missing iteration config"

        iteration_stages = "\n                ".join(
            [f"await self._{stage}()" for stage in spec.iteration.iteration_stages]
        )

        return f'''    async def run(self: "Pipeline") -> bool:
        """Execute iterative workflow.

        Returns:
            True if successful
        """
        max_iterations = {spec.iteration.max_iterations}

        logger.info(f"Starting iteration {{self.state.state.iteration + 1}}/{{max_iterations}}")

        try:
            while self.state.state.iteration < max_iterations:
                logger.info(f"Iteration {{self.state.state.iteration + 1}}")

                {iteration_stages}

                # Check exit conditions
                # TODO: Implement exit condition checks
                # if exit_condition_met:
                #     break

                self.state.state.iteration += 1
                self.state.save()

            logger.info("Completed successfully")
            return True
        except Exception as e:
            logger.error(f"Failed: {{e}}")
            return False
'''

    def _gen_stage_module(self: "SimpleGenerator", spec: ScenarioSpec, stage: Any) -> dict[str, str]:
        """Generate stage module files."""
        module_dir = f"{stage.module_name}/"

        init_content = f'''"""
{stage.display_name}

{stage.description}
"""

from .core import {stage.class_name}

__all__ = ["{stage.class_name}"]
'''

        core_content = f'''"""
{stage.display_name} implementation.
"""

from amplifier.ccsdk_toolkit import ClaudeSession, SessionOptions
from amplifier.utils.logger import get_logger

logger = get_logger(__name__)


class {stage.class_name}:
    """Implements {stage.display_name} functionality."""

    async def {stage.method_name}(self: "{stage.class_name}") -> str:
        """Execute {stage.display_name}.

        Returns:
            Result string
        """
        logger.info("{stage.display_name} starting...")

        # TODO: Implement actual logic
        # Example using Claude:
        # session = ClaudeSession()
        # result = await session.send_message("Your prompt here")
        # return result

        logger.info("{stage.display_name} completed")
        return "placeholder_result"
'''

        return {f"{module_dir}__init__.py": init_content, f"{module_dir}core.py": core_content}


def main() -> None:
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python simple_generator.py <spec_file.json> [output_dir]")
        sys.exit(1)

    spec_path = Path(sys.argv[1])
    if not spec_path.exists():
        print(f"Error: Spec file not found: {spec_path}")
        sys.exit(1)

    output_name = spec_path.stem.replace("_spec", "")
    output_dir = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else Path(__file__).parent.parent.parent.parent / "scenarios" / "_test_generated" / output_name
    )

    print(f"\n{'=' * 60}")
    print(f"Generating scenario from: {spec_path.name}")
    print(f"Output directory: {output_dir}")
    print(f"{'=' * 60}\n")

    generator = SimpleGenerator()
    files = generator.generate_from_spec_file(spec_path, output_dir)

    print(f"✅ Generated {len(files)} files:")
    for file_path in sorted(files.keys()):
        print(f"   - {file_path}")

    print(f"\n🎉 SUCCESS! Scenario generated at:\n   {output_dir}\n")


if __name__ == "__main__":
    main()
